cmake_minimum_required(VERSION 3.10)

if(LITE_WITH_ARM)
  set(ARM_TARGET_OS_LIST "android" "armlinux" "ios" "ios64" "armmacos" "qnx")
  set(ARM_TARGET_ARCH_ABI_LIST "armv8" "armv7" "armv7hf" "arm64-v8a" "armeabi-v7a")
  set(ARM_TARGET_LANG_LIST "gcc" "clang")

  if(NOT DEFINED ARM_TARGET_OS)
    set(ARM_TARGET_OS "armlinux")
  else()
    if(NOT ARM_TARGET_OS IN_LIST ARM_TARGET_OS_LIST)
      message(FATAL_ERROR "ARM_TARGET_OS should be one of ${ARM_TARGET_OS_LIST}")
    endif()
  endif()

  if(NOT DEFINED ARM_TARGET_ARCH_ABI)
    set(ARM_TARGET_ARCH_ABI "armv7hf")
  else()
    if(NOT ARM_TARGET_ARCH_ABI IN_LIST ARM_TARGET_ARCH_ABI_LIST)
      message(FATAL_ERROR "ARM_TARGET_ARCH_ABI should be one of ${ARM_TARGET_ARCH_ABI_LIST}")
    endif()
  endif()

  if(NOT DEFINED ARM_TARGET_LANG)
    set(ARM_TARGET_LANG "gcc")
  else()
    if(NOT ARM_TARGET_LANG IN_LIST ARM_TARGET_LANG_LIST)
      message(FATAL_ERROR "ARM_TARGET_LANG should be one of ${ARM_TARGET_LANG_LIST}")
    endif()
  endif()

  if(ARM_TARGET_LANG STREQUAL "gcc")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -flto")
  endif()

  if(ARM_TARGET_OS STREQUAL "armlinux")
    include(os/armlinux)
  endif()

  set(HOST_C_COMPILER $ENV{CC})
  set(HOST_CXX_COMPILER $ENV{CXX})
  if(NOT HOST_C_COMPILER)
    find_program(HOST_C_COMPILER NAMES gcc PATH /usr/bin /usr/local/bin)
  endif()
  if(NOT HOST_CXX_COMPILER)
    find_program(HOST_CXX_COMPILER NAMES g++ PATH /usr/bin /usr/local/bin)
  endif()
  if(NOT HOST_C_COMPILER OR NOT EXISTS ${HOST_C_COMPILER})
    message(FATAL_ERROR "Cannot find host C compiler. export CC=/path/to/cc")
  endif()
  if(NOT HOST_CXX_COMPILER OR NOT EXISTS ${HOST_CXX_COMPILER})
    message(FATAL_ERROR "Cannot find host CXX compiler. export CXX=/path/to/cxx")
  endif()

  if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Default use Release" FORCE)
  endif()
  if(NOT THIRD_PARTY_BUILD_TYPE)
    set(THIRD_PARTY_BUILD_TYPE "MinSizeRel" CACHE STRING "Default use MinSizeRel" FORCE)
  endif()
endif()

if(NOT APPLE)
  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--as-needed")
endif()

if(ANDROID OR IOS OR ARMLINUX OR ARMMACOS)
  set(WITH_GPU OFF CACHE STRING "Disable GPU when cross-compiling" FORCE)
  set(WITH_DSO OFF CACHE STRING "Disable DSO when cross-compiling" FORCE)
  set(WITH_AVX OFF CACHE STRING "Disable AVX when cross-compiling" FORCE)
  set(WITH_RDMA OFF CACHE STRING "Disable RDMA when cross-compiling" FORCE)
  set(WITH_MKL OFF CACHE STRING "Disable MKL when cross-compiling" FORCE)
endif()
