FILE(GLOB_RECURSE UNIT_TEST_SRC ${CMAKE_CURRENT_SOURCE_DIR}/*test*)

FILE(GLOB_RECURSE FLAT_PARSER_SRC ${CMAKE_CURRENT_SOURCE_DIR}/flatbuffers/*.cc)
if(UNIT_TEST_SRC)
  LIST(REMOVE_ITEM FLAT_PARSER_SRC ${UNIT_TEST_SRC})
endif()

FILE(GLOB MODEL_PARSER_BASE_SRC ${CMAKE_CURRENT_SOURCE_DIR}/*.cc)
if(UNIT_TEST_SRC)
  LIST(REMOVE_ITEM MODEL_PARSER_BASE_SRC ${UNIT_TEST_SRC})
endif()

set(MODEL_PARSER_SRC ${MODEL_PARSER_BASE_SRC} ${FLAT_PARSER_SRC})
set(MODEL_PAESER_DEPS "")

lite_cc_library(model_parser SRCS ${MODEL_PARSER_SRC} DEPS ${MODEL_PAESER_DEPS})
add_dependencies(model_parser fbs_headers)

add_subdirectory(flatbuffers)
