set(op_DEPS core op_params)

# Operators used by SSD MobileNet V1 (intel_fpga)
add_operator(feed_op basic SRCS feed_op.cc)
add_operator(fetch_op basic SRCS fetch_op.cc)
add_operator(scale_op basic SRCS scale_op.cc)
add_operator(softmax_op basic SRCS softmax_op.cc)
add_operator(reshape_op basic SRCS reshape_op.cc)
add_operator(activation_basic_ops basic SRCS activation_ops.cc)
add_operator(conv_op basic SRCS conv_op.cc)
add_operator(elementwise_ops basic SRCS elementwise_ops.cc)
add_operator(multiclass_nms_op_lite basic SRCS multiclass_nms_op.cc)
add_operator(prior_box_op basic SRCS prior_box_op.cc)
add_operator(concat_op basic SRCS concat_op.cc)
add_operator(calib_op basic SRCS calib_op.cc)
add_operator(calib_inplace_op basic SRCS calib_inplace_op.cc)
add_operator(transpose_op basic SRCS transpose_op.cc)
add_operator(unsqueeze_op_lite basic SRCS unsqueeze_op.cc)
add_operator(slice_op_lite basic SRCS slice_op.cc)
add_operator(subgraph_op basic SRCS subgraph_op.cc)
add_operator(io_copy_op basic SRCS io_copy_op.cc)
add_operator(layout_op basic SRCS layout_op.cc)
add_operator(stack_op basic SRCS stack_op.cc)


add_library(ops STATIC ${OPS_SRC} op_params.cc)
add_dependencies(ops utils)
